// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:addu_schedbuilder_flutter/data/local/hive_adapters.dart';
import 'package:addu_schedbuilder_flutter/domain/models/class_data.dart';
import 'package:addu_schedbuilder_flutter/domain/models/class_note.dart';
import 'package:addu_schedbuilder_flutter/domain/models/class_period.dart';
import 'package:addu_schedbuilder_flutter/domain/models/note_type.dart';
import 'package:addu_schedbuilder_flutter/domain/models/notification_config.dart';
import 'package:addu_schedbuilder_flutter/domain/models/saved_schedule.dart';
import 'package:addu_schedbuilder_flutter/domain/models/schedule_row.dart';
import 'package:addu_schedbuilder_flutter/domain/models/schedule_table.dart';
import 'package:addu_schedbuilder_flutter/domain/models/teacher.dart';
import 'package:addu_schedbuilder_flutter/domain/models/theme_preset.dart';
import 'package:addu_schedbuilder_flutter/domain/models/time_slot.dart';
import 'package:addu_schedbuilder_flutter/domain/models/weekday.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BarSlotAdapter());
    registerAdapter(ClassDataAdapter());
    registerAdapter(ClassDataAdapter());
    registerAdapter(ClassNoteAdapter());
    registerAdapter(ClassNoteAdapter());
    registerAdapter(ClassPeriodAdapter());
    registerAdapter(ClassPeriodAdapter());
    registerAdapter(ClassSlotAdapter());
    registerAdapter(ColorDataAdapter());
    registerAdapter(ColorDataAdapter());
    registerAdapter(EmptySlotAdapter());
    registerAdapter(NoteTypeAdapter());
    registerAdapter(NoteTypeAdapter());
    registerAdapter(NotificationConfigAdapter());
    registerAdapter(NotificationConfigAdapter());
    registerAdapter(SavedScheduleAdapter());
    registerAdapter(SavedScheduleAdapter());
    registerAdapter(ScheduleRowAdapter());
    registerAdapter(ScheduleRowAdapter());
    registerAdapter(ScheduleTableAdapter());
    registerAdapter(ScheduleTableAdapter());
    registerAdapter(TeacherAdapter());
    registerAdapter(TeacherAdapter());
    registerAdapter(ThemePresetAdapter());
    registerAdapter(ThemePresetAdapter());
    registerAdapter(TimeAdapter());
    registerAdapter(TimeSlotAdapter());
    registerAdapter(WeekdayAdapter());
    registerAdapter(WeekdayAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BarSlotAdapter());
    registerAdapter(ClassDataAdapter());
    registerAdapter(ClassDataAdapter());
    registerAdapter(ClassNoteAdapter());
    registerAdapter(ClassNoteAdapter());
    registerAdapter(ClassPeriodAdapter());
    registerAdapter(ClassPeriodAdapter());
    registerAdapter(ClassSlotAdapter());
    registerAdapter(ColorDataAdapter());
    registerAdapter(ColorDataAdapter());
    registerAdapter(EmptySlotAdapter());
    registerAdapter(NoteTypeAdapter());
    registerAdapter(NoteTypeAdapter());
    registerAdapter(NotificationConfigAdapter());
    registerAdapter(NotificationConfigAdapter());
    registerAdapter(SavedScheduleAdapter());
    registerAdapter(SavedScheduleAdapter());
    registerAdapter(ScheduleRowAdapter());
    registerAdapter(ScheduleRowAdapter());
    registerAdapter(ScheduleTableAdapter());
    registerAdapter(ScheduleTableAdapter());
    registerAdapter(TeacherAdapter());
    registerAdapter(TeacherAdapter());
    registerAdapter(ThemePresetAdapter());
    registerAdapter(ThemePresetAdapter());
    registerAdapter(TimeAdapter());
    registerAdapter(TimeSlotAdapter());
    registerAdapter(WeekdayAdapter());
    registerAdapter(WeekdayAdapter());
  }
}
