import 'package:hive_ce_flutter/hive_flutter.dart';
import 'package:path_provider/path_provider.dart';
import '../../domain/models/class_note.dart';
import '../../domain/models/notification_config.dart';
import '../../domain/models/saved_schedule.dart';
import '../../domain/models/theme_preset.dart';

/// Initialize Hive CE with all type adapters
Future<void> initHive() async {
  // Get application directory for Hive storage
  final appDir = await getApplicationDocumentsDirectory();

  // Initialize Hive with the app directory
  await Hive.initFlutter(appDir.path);

  // Register all type adapters (generated by hive_ce_generator)
  // These are registered automatically via hive_registrar.g.dart
  // But we'll register them manually here for clarity

  // Note: The actual adapters are auto-registered by importing hive_registrar.g.dart
  // This function mainly handles opening the boxes

  // Open boxes for each entity type
  await Hive.openBox<SavedSchedule>('schedules');
  await Hive.openBox<ClassNote>('notes');
  await Hive.openBox<ThemePreset>('theme_presets');
  await Hive.openBox<NotificationConfig>('notification_config');
}

/// Close all Hive boxes (call on app disposal)
Future<void> closeHive() async {
  await Hive.close();
}

/// Get a box by name (type-safe)
Box<T> getBox<T>(String name) {
  return Hive.box<T>(name);
}
