// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:addu_schedbuilder_flutter/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BarSlotAdapter());
    registerAdapter(ClassDataAdapter());
    registerAdapter(ClassNoteAdapter());
    registerAdapter(ClassPeriodAdapter());
    registerAdapter(ClassSlotAdapter());
    registerAdapter(ColorDataAdapter());
    registerAdapter(EmptySlotAdapter());
    registerAdapter(NoteTypeAdapter());
    registerAdapter(NotificationConfigAdapter());
    registerAdapter(SavedScheduleAdapter());
    registerAdapter(ScheduleRowAdapter());
    registerAdapter(ScheduleTableAdapter());
    registerAdapter(TeacherAdapter());
    registerAdapter(ThemePresetAdapter());
    registerAdapter(TimeAdapter());
    registerAdapter(WeekdayAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BarSlotAdapter());
    registerAdapter(ClassDataAdapter());
    registerAdapter(ClassNoteAdapter());
    registerAdapter(ClassPeriodAdapter());
    registerAdapter(ClassSlotAdapter());
    registerAdapter(ColorDataAdapter());
    registerAdapter(EmptySlotAdapter());
    registerAdapter(NoteTypeAdapter());
    registerAdapter(NotificationConfigAdapter());
    registerAdapter(SavedScheduleAdapter());
    registerAdapter(ScheduleRowAdapter());
    registerAdapter(ScheduleTableAdapter());
    registerAdapter(TeacherAdapter());
    registerAdapter(ThemePresetAdapter());
    registerAdapter(TimeAdapter());
    registerAdapter(WeekdayAdapter());
  }
}
